### PR TITLE
Task comments

### PR DESCRIPTION
**Pull request by vojkog**

### CODE REVIEW

**Comment by MTwelkemeier** [comment]
Thank you for your merge request of #16. I will have a look into the changes.

**Comment by MTwelkemeier** [comment]
The pull request looks great. Do you already have some ideas to test the new event?

**Comment by vojkog** [comment]
> The pull request looks great. Do you already have some ideas to test the new event?
Thank you. I'll try to add a test similar to existing ones.

**Comment by MTwelkemeier** [comment]
Issue #15 should be solved now: SonarCloud will be skipped for external pull requests.
Unfortunately, this seems to have no affect on this existing pull request when just restarting the CI build.

**Comment by vojkog** [comment]
Added junit test proposal for TASK_COMMENTS.

**Comment by MTwelkemeier** [comment]
The test looks good. Thank you for your contribution!
After resolving the merge conflict, I think we can merge this enhancement.

Off topic: Currently, there is no central code formatting. In the past we faced some problems regarding different formatting of different users. I created issue #20 to provide a central formatting to make it as easy as possible for all contributions.

**Pull request merged**
