### PR TITLE
Update to latest Camunda version 7.10.0

### PR DESCRIPTION
**Pull request by vojkog**

### CODE REVIEW

**Comment by MTwelkemeier** [comment]
The merge request looks good. 

I just removed the first commit which adds mysql dependency, since there is the dedicated merge request #23 for this enhancement. 

Additionally I moved the default value for `polling.camunda.jdbc.historyLevel` directly into the properties attribute. The problem that default values of these attributes did not work seem to be related to our usage of environment property references within the application properties (e.g. `${CAMUNDA_JDBC_URL:}`). Using those references will at least provide an empty value, which overwrites the default value of our attribute.

**Comment by MTwelkemeier** [comment]
Unfortunately, I had to rebase to drop the initial MySQL dependency commit. The modified branch is now merged into develop, but this merge commit can no longer track this merge. Thus closing the merge request manually.

**Comment by vojkog** [comment]
Thanks once again for your time and support!

**Comment by MTwelkemeier** [comment]
You are welcome. Thank you for your contribution.

**Pull request closed without merging**
